name: simplw-whale
on:
  push:

jobs:
  build_test:
    runs_on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Run the image in a container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/simplewhale:latest
          run: |
            echo "runing the docker image"
            echo "Testing the nodejs  app endpoints"
            # echo ${{ steps.docker_build.outputs.digest }}